include:
  # shells and build related services
  - .docker/carapace.yaml
  # tools
  - .docker/apk.yaml
  - .docker/bloop.yaml
  - .docker/brew.yaml
  - .docker/cmd-clink.yaml
  - .docker/fzf-tab.yaml
  - .docker/gcloud.yaml
  - .docker/nix.yaml
  - .docker/redhat.yaml
  - .docker/ubuntu.yaml
  - .docker/xbps.yaml
  # issues
  - .docker/issue-2781.yaml # infinite recursion in fish
